spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fcbarca1899
    url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
    serialization:
      indent_output: true
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 127.0.0.1:9300
  data:
    #ElasticSearch的连接地址
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
server:
  port: 8090

aliyun:
  sms:
    accessKeyId: LTAI4GDhc7Z4bSZDevtpd7V6
    accessKeySecret: UEcWaql7VZItlPDSH99QIQdm3y0xDl
    product: Dysmsapi
    domain: dysmsapi.aliyuncs.com
    regionId: cn-hangzhou
    signName: 品牌服饰空中商城
    dateFormat: yyyyMMdd
    endpointName: cn-hangzhou
##支付宝支付配置
#alipayconfig:
#  #商户APPID
#  appId: 2016102200738123
#  #私钥 pkcs8格式的
#  rsaPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDcc0J3tdSIXdkfjC5+YLlwLeCJwQ/bFbmoXGr+UE5YowIELogLYyar32pLZqnNyl8AhV2+HdA3VhYbq+MQ8ZJFCDAdkq+7waqu3QVc+BvcKPRjN39z9vn14UGncd5Iii2SyNKoawYxjJ6gH7cq8dLAyBCHHrDud0WCz/aXBDCU4WJmPy+4Ay8/KdJvCNiQ9DBQ/ygSdX0XFZVypSYdY25paYF3jmjsoGAHFiKyKjfK9iTrPGGmGQxfE3NuTH0n5KDZobnr4hKB9gq1RLcVPXGYMmf3qOXcgBb6JSqa78JZ8wmXgb3vyJdGfrBtF81xLEbtwJ12YdlTtPTgUGRoXeTNAgMBAAECggEAbQXHemJ/UE1xYou2NqPpMZROtnG3QLcW0S+bblgS1v0Oszi76T3I0zkzXUTRd0e9Agny2WHvJl65oke4jRmbJ+6rtQRlSmq12bLOwzKkvJW4fxTkQFqFNdeH26KRtrg3X59Xpxj+wCR2EmR89o0PmG2Y1uoTwGtWAiKNJhRZXlbJkEFylHdxNFEyNmNd7Yjslc3Ndw4K4ViHT6CCRzGgwzmQAjf0q4XBZcRSi6MUc7gTCrVCG3FP3DBQB8pNDhN2ZAtm+kDFNKX6fC1FUbjTwr2QBGhE56PY4PrWmCxa3og/gCzAC6dzkwVkPdeC8LtxGG3NPcN89bFwQD5+qkerIQKBgQDwlLut18lfGZ3ucpAQRPrv19bIUvJpT/1rk4vN8y8eigFsIjnpquNQEikRYr+KWmo7xNs9pR7kxGUbt6NKoGZqar0GQC7qAzVLabKFw+awbf4BrF46Dy+fInf4m/hyZ8QQIMK43nYL6K06LIPDxJswUCRhVmHMVDdjq5wdQdcIOQKBgQDqlDyUYgPCCrAuJCA4qZCUS3w3DEgtom8ZBcuhm6LeTvaSRjx4d9kgY7ae1DPGIdFHGNbGdq+dGWFel6QEZA5XfA/X85QjDr/+7r/Lg2ogOjRgt8y77nt4vomls6dc4HlY0+BDWDVBOBJAbf81AvNAv2Ceg0d8yu4tZPVe4Si5NQKBgQCLVGgZNyatiAV6Kika8wgtTWBbpgY0TZoj6lCGVveMBTrrqCrIFCsPnWThZ8IsW065DLo4Sl/I96Di24ibWKfXq7eLXjKNXoxH/4/ffmQk+56m02/Cyja3P9whRBswDr5y5LZBIL1XCksArPUmtL93zII1STTchE2L0MBaBV6GqQKBgQCnKnItT9fbvOAmUYpAtt2YQF7Jn9AD7UB8tXuStCWRhPYD8VeAhe/OPCDU+OXYaRsJLnNHxSaKrp6L2UaB9oed4oQr4aIMhaNe2ecF8aV8R94xmmmk92M3/Zh75BX9gt4W5g5oD4EL9BhVn82BipOs7XS+IVGdZcPrx4lwTsZFjQKBgQC6dvn3lBYXOnTWGmRP3mGEWTjgPec6XUexFnvp4XvlZOqQKnCV/6Gao/4zr1nzrOxsx0uTk6RinyAhY30NakdpD1fJbzk2PeeH8Hl3uUOhL9lbgLj/T4YRLiGeiOjlsHR4I2boNlXBS0aYlhILryjQn4/8VMh2AJG7aBHKiiJNuw==
#  #请求网关地址
#  url: https://openapi.alipaydev.com/gateway.do
#  #编码
#  charset: UTF-8
#  #返回格式
#  format: JSON
#  #支付宝公钥
#  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkI9jeRSQSdxigA/STrtYXL7wMrWVKat3gkAfO+geWU394+pZRANRCtcCuhyxe0CrYyWz7oCrHrZcEeuJ3wpZcVCtNLiH7yLlVcd1z3VDcG9EWwh3RtiMAgT6S60ssnxbweRn4Li+7YkLY7Gvi+7wF8UNJk0PyrP+fMlbkbTE3XExphmApbX57puLBWsMVLpnLRhvfCKZAvTTkelVi0pd2L38htN3GIoGnJ6HHQ6+J8t0xMELug3Hz2Ga32jPytoI2nBkIj987TIaftQK61TfAErhJa/CB7XzlQZzyXJVMFXJlC0V+iTLrVcl4fc5whToh6SS05MQ4zq8u0WCT2fAwQIDAQAB
#  #签名方式
#  signType: RSA2
